name: GO_TEST_BUILD

on:
  push:
    branches: [feature/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build
      run: go build -v ../..
    - name: Echo out success
      run: echo 'Building Success'