name: Scheduled Cron Job

on:
  schedule:
    - cron: '32 5 * * 1,3'
    - cron: '30 8 * * *'
    - cron: '0 0 * * *'

jobs:
  testing_cron_schedule_template:
    runs-on: ubuntu-latest
    steps:
      - name: Everyday except Monday and Wednesday
        if: github.event.schedule != '32 5 * * 1,3'
        run: echo 'Skipping these on Monday and Wednesday'
      - name: Every 3 minutes
        if: github.event.schedule == '0 0 * * *'
        run: echo 'cron job running once daily'
      - name: Every Time
        run: echo 'This will run every time at $(date)'
