name: Create and Publish Open API specs
on:
  push:
    branches:
      - 'SpecFeature/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish_github_pages:
    runs-on: 'ubuntu-latest'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Build API docs
        run : redocly build-docs ./docs/open-api.yaml -o ./docs/open-api.html
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Publish to Github pages
        id: deployment
        uses: actions/deploy-pages@v4