name: CI pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  Generate_Nuget_Package:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '9.0.x'
      - name: Create test dir
        run: |-
          mkdir -p ./generated-sdk
        id: generate_sdk
      - name: Generate SDK
        run: |-
          echo 'Generating SDK ....'
          dotnet new classlib -n SmotwSdk --output ./generated-sdk
          cd ./generated-sdk
          dotnet pack
          ls ./bin/Release
  Generate_Nuget_Package_using_script:
    runs-on: 'ubuntu-latest'
    outputs:
      package_path: ${{ steps.generate_sdk.outputs.package_path }}
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x # invisible to dependabot
      - name: Set up .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '9.0.x'
      - name: run scripts
        run: |-
          chmod +x ./scripts/populate-data.sh
          ./scripts/populate-data.sh
        id: generate_sdk
  Generate_Nuget_Package_using_inline_script:
    runs-on: 'ubuntu-latest'
    outputs:
      package_path: ${{ steps.generate_sdk_inline.outputs.package_path }}
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          sparse-checkout: |
            scripts/populate-data.sh
          sparse-checkout-cone-mode: false
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x # invisible to dependabot
      - name: Set up .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '9.0.x'
      - name: run scripts
        run: |-
          chmod +x ./scripts/populate-data.sh
          ./scripts/populate-data.sh
        id: generate_sdk_inline
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ${{ needs.Generate_Nuget_Package_using_inline_script.outputs.package_path }}
  Display_from_gh_var:
    runs-on: 'ubuntu-latest'
    needs: Generate_Nuget_Package_using_inline_script
    steps:
      - name: use package path
        run: echo "Package is at ${{ needs.Generate_Nuget_Package_using_inline_script.outputs.package_path }}"
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package
      - name: display artifact
        run: |
          echo "Artifact is at ${{ needs.Generate_Nuget_Package_using_inline_script.outputs.package_path }}"
          ls -la ${{ needs.Generate_Nuget_Package_using_inline_script.outputs.package_path }}
          cat ${{ needs.Generate_Nuget_Package_using_inline_script.outputs.package_path }}
    